name: build/electron
run-name: Building and releasing electron app 🚀
on: [push, pull_request]

jobs:
  release:
    if: ${{ github.ref == 'ref/heads/main' || github.event.label.name == 'create-build' }}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-13, macos-latest, windows-latest]
    env:
      DEBUG: electron-builder
      GH_TOKEN: ${{ secrets.github_token }}
    steps:
      - name: Set outputs
        id: vars
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Check out Git repository
        uses: actions/checkout@v1

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v1
        with:
          node-version: 20

      - name: "npm install"
        run: npm install
      - name: "npm build"
        run: npm run build
      - name: "electron-builder"
        run: npx electron-builder --publish never

      - name: "Upload mac artifact"
        if: ${{ matrix.os == 'macos-latest' }}
        uses: actions/upload-artifact@v4
        with:
          name: CTT_MacOS_arm64_${{ steps.vars.outputs.sha_short }}
          path: |
            dist/*.dmg
            dist/*.dmg.blockmap
            dist/*.yml

      - name: "Upload mac artifact"
        if: ${{ matrix.os == 'macos-13' }}
        uses: actions/upload-artifact@v4
        with:
          name: CTT_MacOS_amd64_${{ steps.vars.outputs.sha_short }}
          path: |
            dist/*.dmg
            dist/*.dmg.blockmap
            dist/*.yml

      - name: "Upload windows artifact"
        if: ${{ startsWith(matrix.os, 'win') }}
        uses: actions/upload-artifact@v4
        with:
          name: CTT_Windows_64_${{ steps.vars.outputs.sha_short }}
          path: dist
