name: build/electron
run-name: Building and releasing electron app 🚀
on: [push]
jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-13, macos-latest, windows-latest]
    env:
      DEBUG: electron-builder
      GH_TOKEN: ${{ secrets.github_token }}
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v1
        with:
          node-version: 20

      # runs:
      #   using: node12
      #   main: builder.js
      - name: "npm install"
        run: npm install
      - name: "npm build"
        run: npm run build
      - name: "electron-builder"
        run: npx electron-builder --publish never

      # - name: Build/release Electron app
      #   uses: samuelmeuli/action-electron-builder@v1
      #   with:
      #     # GitHub token, automatically provided to the action
      #     # (No need to define this secret in the repo settings)
      #     github_token: ${{ secrets.github_token }}
      #     # args: --publish always
      #     # args: DEBUG=electron-builder
      #     # If the commit is tagged with a version (e.g. "v1.0.0"),
      #     # release the app after building
      #     # release: true
      #     # release: ${{ startsWith(github.ref, 'refs/tags/v') }}

      # - run: mkdir -p path/to/artifact
      # - run: echo hello > path/to/artifact/world.txt
      - name: "Upload mac artifact"
        if: ${{ matrix.os == 'mac-latest' }}
        uses: actions/upload-artifact@v4
        with:
          name: CourseTerrainTool_MacOS_arm64
          path: |
            dist/*.dmg
            dist/*.dmg.blockmap
            dist/*.yml

      - name: "Upload mac artifact"
        if: ${{ matrix.os == 'mac-13' }}
        uses: actions/upload-artifact@v4
        with:
          name: CourseTerrainTool_MacOS_x86_64
          path: |
            dist/*.dmg
            dist/*.dmg.blockmap
            dist/*.yml

      - name: "Upload windows artifact"
        if: ${{ startsWith(matrix.os, 'win') }}
        uses: actions/upload-artifact@v4
        with:
          name: CourseTerrainTool_Windows64
          path: dist
